spring:
  application:
    name: movie
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5434/movie_db
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
      jdbc:
        lob:
          non_contextual_creation:
            true
server:
  port: 8085


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
