spring:
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8080
  application:
    name: review
  datasource:
    url: jdbc:postgresql://localhost:5434/review_db
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
      jdbc:
        lob:
          non_contextual_creation:
            true
server:
  port: 8081


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka


# service uris

service:
  user:
    location: http://localhost:8083/api/users
  movie:
    location: http://localhost:8085/api/movies