spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8080
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/users/**
        - id: movie
          uri: lb://MOVIE
          predicates:
            - Path=/api/movies/**
        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/api/reviews/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
  instance:
    hostname: localhost

server:
  port: 8084